# -*- coding: utf-8 -*-
"""analysis customer data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eph0vcb8yXgFsr6oMitRmxFtClvRPU64
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- TASK 1: Data Generation ---
np.random.seed(42)  # For reproducibility
n_records = 500

data = {
    'Customer_ID': range(1, n_records + 1),
    'Age': np.random.randint(18, 76, size=n_records),
    'Purchase_Amount': np.round(np.random.uniform(10.0, 500.0, size=n_records), 2),
    'Product_Category': np.random.choice(['Electronics', 'Apparel', 'Groceries'], size=n_records)
}

df = pd.DataFrame(data)

# --- TASK 2: Data Cleaning & Quality Checks ---
print("--- Data Quality Checks ---")
print(f"Missing Values:\n{df.isnull().sum()}\n")
print(f"Data Types:\n{df.dtypes}\n")

# --- TASK 3: Descriptive Statistics ---
stats_age = df['Age'].describe()
stats_purchase = df['Purchase_Amount'].describe()
category_counts = df['Product_Category'].value_counts()

print("--- Descriptive Statistics ---")
print(f"Age Stats:\n{stats_age[['mean', '50%', 'std', 'min', 'max']]}")
print(f"\nPurchase Amount Stats:\n{stats_purchase[['mean', '50%', 'std', 'min', 'max']]}")
print(f"\nProduct Category Frequency:\n{category_counts}")

# --- TASK 4: Visualizations ---
plt.figure(figsize=(12, 5))

# Visualization 1: Histogram of Purchase Amount
plt.subplot(1, 2, 1)
sns.histplot(df['Purchase_Amount'], bins=20, kde=True, color='skyblue')
plt.title('Distribution of Purchase Amount')
plt.xlabel('Amount ($)')
plt.ylabel('Frequency')

# Visualization 2: Bar Plot of Average Purchase by Category
plt.subplot(1, 2, 2)
sns.barplot(x='Product_Category', y='Purchase_Amount', data=df, estimator=np.mean, palette='viridis')
plt.title('Avg Purchase Amount by Category')
plt.xlabel('Category')
plt.ylabel('Mean Purchase ($)')

plt.tight_layout()
plt.show()